# syntax=docker/dockerfile:1
FROM python:3
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
EXPOSE 8000
WORKDIR /code
RUN apt-get update
RUN pip install uwsgi
RUN mkdir -p /etc/uwsgi/sites
COPY requirements.txt /code/
RUN pip install --no-cache-dir -r requirements.txt
COPY . /code/
COPY app.ini /etc/uwsgi/sites/
CMD [ "uwsgi", "--http", "0.0.0.0:8000", \
               "--plugins", "python3", \
               "--module","gasdeliverybackend" ]
# RUN /usr/local/bin/uwsgi --emperor /etc/uwsgi/sites
# RUN /usr/local/bin/uwsgi --http 0.0.0.0:8000 --module gasdeliverybackend
