# syntax=docker/dockerfile:1
FROM python:3
# ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
WORKDIR /code
RUN sudo apt install python3-dev python3-pip nginx git
RUN pip install uwsgi
RUN mkdir -p /etc/uwsgi/sites
COPY requirements.txt /code/
RUN pip install -r requirements.txt
COPY app.ini /etc/uwsgi/sites/
COPY delivery.app.nginx /etc/nginx/sites-available/
RUN rm /etc/nginx/sites-enabled/default
RUN ln -s /etc/nginx/sites-available/delivery.app.nginx /etc/nginx/sites-enabled/
RUN systemctl enable nginx
COPY app.service /etc/systemd/system/
RUN systemctl enable uwsgi
COPY . /code/