# Generated by Django 3.1.4 on 2020-12-30 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(default='f80ddc92-79ce-486e-a989-57c8b8376964', max_length=255, verbose_name='Order ID')),
                ('amount', models.IntegerField(verbose_name='Amount')),
                ('pickup_address', models.CharField(max_length=255, verbose_name='Pickup Address')),
                ('dropoff_address', models.CharField(max_length=255, verbose_name='DropOff Address')),
                ('order_status', models.CharField(choices=[(0, 'DELIVERED'), (1, 'CANCELLED'), (2, 'PENDING')], max_length=255, verbose_name='Order Status')),
                ('package_size_in_kg', models.CharField(max_length=255, verbose_name='Size of Package in Kg')),
                ('description', models.TextField(verbose_name='Order Description')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_delivered', models.DateTimeField(null=True)),
                ('is_delivered', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_accepted', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VendorProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_id', models.CharField(default='a52ff843-29d5-4ac7-8a77-ce512c6bd7c5', max_length=255, verbose_name='Order ID')),
                ('business_name', models.CharField(max_length=255, verbose_name='Business Name')),
                ('opening_time', models.IntegerField(default=8, verbose_name='Opening Time')),
                ('closing_time', models.IntegerField(default=6, verbose_name='Closing Time')),
                ('price_per_kg', models.IntegerField(default=6, verbose_name='Price Per Kg')),
                ('is_taking_orders', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='v_data', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_id', models.CharField(default='c1772dee-c272-446a-9327-2db84dbcc5ae', max_length=255, verbose_name='Review ID')),
                ('ratings', models.CharField(choices=[(1, 'ABYSMAL'), (2, 'POOR'), (3, 'AVERAGE'), (4, 'GOOD'), (5, 'EXCELLENT')], max_length=255, verbose_name='Ratings')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='main.order')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField(verbose_name='Text')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='main.reviews')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
