# Generated by Django 3.1.4 on 2020-12-30 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.FloatField(default=100.0, max_length=255, verbose_name='Balance')),
                ('wallet_id', models.CharField(default='6f5151a2-2150-4e49-a280-15dbe4898b3c', max_length=255, verbose_name='Wallet ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(default='7f17561b-79c6-439a-bb01-0428e64b050d', max_length=255, verbose_name='Transaction ID')),
                ('amount', models.FloatField(default=0.0, verbose_name='Amount')),
                ('status', models.CharField(default='failed', max_length=255, verbose_name='Status')),
                ('reference', models.CharField(default='5f44337f-e763-4ac0-8e10-cca63015ec14', max_length=255, verbose_name='Reference')),
                ('origin', models.CharField(default='wallet', max_length=255, verbose_name='Origin')),
                ('trans_type', models.CharField(default='credit', max_length=255, verbose_name='Transaction Type')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wallet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='wallet.wallet', verbose_name='Wallet')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.CharField(default='ed43a7c5-4972-48d9-a697-6f524df87faf', max_length=255, verbose_name='card_id')),
                ('auth_ref', models.CharField(max_length=255, null=True, unique=True, verbose_name='Authentication Reference')),
                ('ref_code', models.CharField(max_length=255, unique=True, verbose_name='Transaction Reference')),
                ('verified', models.BooleanField(default=False, verbose_name='Verified')),
                ('reusable', models.BooleanField(default=False, verbose_name='Reusable')),
                ('card_type', models.CharField(max_length=255, null=True, verbose_name='Card Type')),
                ('origin', models.CharField(default='paystack', max_length=255, verbose_name='Name')),
                ('last4', models.CharField(max_length=255, null=True, verbose_name='Last4')),
                ('exp_month', models.CharField(max_length=255, null=True, verbose_name='Expiry Month')),
                ('exp_year', models.CharField(max_length=255, null=True, verbose_name='Expiry Year')),
                ('first6', models.CharField(max_length=255, null=True, verbose_name='Bin')),
                ('bank', models.CharField(max_length=255, null=True, verbose_name='Bank')),
                ('signature', models.CharField(max_length=255, null=True, verbose_name='Signature')),
                ('country_code', models.CharField(max_length=255, null=True, verbose_name='Country Code')),
                ('customer_id', models.IntegerField(null=True, verbose_name='Customer Id')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
